# My first ever action, probably won't even work lol

name: Build and test with make + QEMU

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: build, install and test project
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: i686-elf-tools
        key: i686-elf-tools

    - name: install i686-elf-tools
      if: steps.i686-elf-tools.outputs.cache-hit != 'true'
      run: |
        wget 'https://docs.google.com/uc?export=download&id=1a6Ev045HlVWSk8Ake2DPWnpHxSxEzDhS' -O i686-elf-tools.tar.xz
        tar xf i686-elf-tools.tar.xz

    - name: install qemu
      run: |
        sudo apt update
        sudo apt install -y qemu-system-x86 nasm

    - name: create device
      run: |
        dd if=/dev/zero of=dev.o bs=4096 count=131072
        mkfs.fat -F32 dev.o
        mkdir dev.d
        sudo mount -o uid=$(id -u),gid=$(id -g) dev.o dev.d

    - name: make build, install and test
      run: |
        ls -la
        pwd
        export PATH="$HOME/i686-elf-tools/bin:$PATH"
        make build
        make install
        make test

    - name: make build, install and test (debug configuration)
      run: |
        export PATH="$HOME/i686-elf-tools/bin:$PATH"
        export DEBUG=y
        make build
        make install
        make test
