# My first ever action, probably won't even work lol

name: Build and test with make + QEMU

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: build, install and test project
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: make build, install and test
      run: |
        make build
        make install
        make test

  test-debug:
    name: build, install and test debug configuration
    runs-on: ubuntu-18.04
    
    env:
      DEBUG: Y

    steps:
    - uses: actions/checkout@v2
    - name: make build, install and test (debug)
      run: |
        DEBUG=Y make build
        DEBUG=Y make install
        DEBUG=Y make test
